# Use postgres/example user/password credentials
version: '3.8'

services:
  ucenter:
    container_name: ucenter
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - nest-postgres:/var/lib/postgresql/data

volumes:
  redis:
    driver: local
  nest-postgres:
    name: ucenter-postgres